learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),#will look at url file in app and execute whats in there
    path('users/', include('users.urls'))
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'

#'' null is the homepage
## 1 set up URL
urlpatterns = [
    path('', views.index, name = 'index'), #'' is the homepage
    path('topics', views.topics, name = 'topics'), #this would be homepage/topics/html (1)
    path('topics/<int:topic_id>/', views.topic, name = 'topic'),
    path('new_topic/', views.new_topic, name = 'new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name = 'new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name = 'edit_entry'),
]

users/urls.py
from django.urls import path,include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name = 'register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# Create model of database

class Topic(models.Model):
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self): #returns the text related to the text field
        return self.text 


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE) 
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta: #does entry as plural to be correct in the site
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic
from .models import Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}

        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Topic, Entry #import from models.py file
from .forms import TopicForm
from .forms import EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
# Defined as functions
# 2

def index(request):
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request): #(2) get all topics
    topics = Topic.objects.filter(owner = request.user).order_by('date_added')

    context = {'topics':topics} #allows to use template variables

    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id): #integer made in url - get individual topic
    topic = get_object_or_404(Topic, id = topic_id)

    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added') # - is decending order

    context = {'topic': topic, 'entries': entries}

    return render(request, 'learning_logs/topic.html', context) 

#TWO TYPES REQUEST
#GET - get data (loading up with empty fields, no info)
#POST - post data (send info to DB)
@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else: #request is not blank
        form = TopicForm(data = request.POST) 

        if form.is_valid():#if the form is actually valid
            new_topic = form.save(commit=False) #what view will use to take the info and save to DB
            new_topic.owner = request.user #specify who the user will be
            new_topic.save()

            return redirect("learning_logs:topics")

    context= {'form': form}

    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id = topic_id)
    
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)

        if form.is_valid():
            new_entry = form.save(commit = False)

            new_entry.topic = topic
            new_entry.save()
            form.save()
            return redirect('learning_logs:topic', topic_id = topic_id)
    
    context = {'form':form, 'topic':topic}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id): #has to match the views.entry
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic #since it is an attribute of entry

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance = entry)
    else:
        form = EntryForm(instance = entry, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id = topic.id)
            
    context = {'entry':entry, 'topic':topic, 'form':form} #is a dictionary that is used to pass information to the html
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')

    context = {'form':form}
    return render(request, 'registration/register.html',context)

learning_logs/templates/learning_logs/base.html
<!-- Updated base -->
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
            Learning Log</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                    Topics</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                 </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
            {% endif %}
        </ul>
    </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry:</p>

<form action = "{% url 'learning_logs:edit_entry' entry.id %}" method = 'post'>
    {% csrf_token %}

    {{ form.as_p }}

    <button name = "submit">Save Changes</button>

</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Track your learning.</h1>
        <p class="lead">Make your own Learning Log, and keep a list of the topics
            you're learning about. Whenever you learn something new about a topic,
            make an entry summarizing what you've learned.</p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>

<form action = "{% url 'learning_logs:new_entry' topic.id %}" method = 'post'>
    {% csrf_token %}

    {{ form.as_p }}

    <button name = "submit">Add entry</button>

</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Add a new topic:</p>

<form action = "{% url 'learning_logs:new_topic' %}" method = 'post'>
    {% csrf_token %}

    {{ form.as_p }}

    <button name = "submit">Add topic</button>

</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
    <p>
        <a href = "{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>

    {% for e in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ e.date_added|date:'M d, Y H:i' }}
                <small><a href="{% url 'learning_logs:edit_entry' e.id %}">
                    edit entry</a></small>
            </h4>
            <div class="card-body">
                {{ e.text|linebreaks }}
            </div>
        </div>

    {% empty %}
        <p> There are no entries for this topic yet.</p>
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

<ul>
    {% for topic in topics %}
        <li><h3>
            <a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }} </a>
        </h3></li>
    {% empty %}
        <li><h3> No topics have been added yet.</h3></li>
    {% endfor %}
</ul>

<h3><a href = "{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}